version: "3.9"

networks:
  dev_network:

volumes:
  mysql_db_data:
  mysql_db_data2:

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    volumes:
      - mysql_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    networks:
      - dev_network

  mysql_db2:
    image: mysql:latest
    container_name: mysql_db2
    volumes:
      - mysql_db_data2:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3307:3306
    networks:
      - dev_network

  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    networks:
      - dev_network
