version: "3.9"

services:
  postgres_db:
    image: postgres:latest
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    networks:
      - dev_network

  pgadmin4:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres_db
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@localhost.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    networks:
      - dev_network

networks:
  dev_network:

volumes:
  postgres_db_data:
